### ISSUE TITLE
Stop working since 3.1.0

### ISSUE THREAD

**Issue by nagman** [wkillerud/some-sass#142]
- VS Code version: 1.88.1
- Extension version: 3.1.1
- Operating system: Macos 14.4.1

The plugin just stopped working today. I thought it was due to installing another plugin, but I could not make some sass work again even after uninstalling the other plugin.

So I rolled back the version to 3.1.0, still no success. Then 3.0.1, and it worked.

**Comment by wkillerud** [comment]
It works fine in my testing so you have to be more specific. A GitHub repo with Sass code that demonstrates a bug or a crash will make it a lot easier for me to help.

**Comment by xavieraijon** [comment]
Same issue, last updates not working on my VSCode, and duplicates all properties:
<img width="337" alt="image" src="https://github.com/wkillerud/some-sass/assets/568658/cc3b5005-fbdd-4f6d-9668-bbb0b98006dc">

**Comment by wkillerud** [comment]
I can't help without a GitHub repo with Sass code that demonstrates a bug or a crash.

If you can't link to an example Sass repo that shows the problem you can try to debug the problem yourself:

- [Development environment](https://wkillerud.github.io/some-sass/contributing/development-environment.html) (Node and VS Code)
- [Debugging](https://wkillerud.github.io/some-sass/contributing/debugging.html)

**Comment by xavieraijon** [comment]
Issue fixed in latest version, thx!
