### ISSUE TITLE
No intellisense/autocompletion on neovim

### ISSUE THREAD

**Issue by hambergerpls** [wkillerud/some-sass#163]
- VS Code version: -
- Extension version: -
- Operating system: WSL2 NixOS

Reproducible Case:
The LSP does not produce any intellisense, completions or hovering documentations when installed via Mason in Neovim

Steps to Reproduce:
1. Install somesass_ls via Mason
2. Restart Neovim
3. Create a test.scss file
4. Type `@`, no suggestions shown. (expected a list of At-Rules shown)

**Comment by simeonoff** [comment]
@hambergerpls Can't reproduce on my end.

<img width="1007" alt="Screenshot 2024-05-20 at 10 29 50" src="https://github.com/wkillerud/some-sass/assets/4118303/cad766e2-71f4-4fa6-9a63-74f3d0d7c084">

Can you provide a link to your dotfiles/config?

**Comment by hambergerpls** [comment]
@wkillerud hm, that is strange.

Here's my Neovim config: https://github.com/hambergerpls/kickstart-modular.nvim
