### ISSUE TITLE
Look into replacing Webpack with esbuild

### ISSUE THREAD

**Issue by wkillerud** [wkillerud/some-sass#169]
The VS Code extension generator now has an option to use `esbuild`. There are samples and docs that explain the setup.

The webpack build is fairly slow, so I'd be interested to see if it can be replaced with esbuild to speed things up a bit.

- [esbuild-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/esbuild-sample)
- [Web extensions: esbuild](https://code.visualstudio.com/api/extension-guides/web-extensions#using-esbuild)
- [Extensions: esbuild](https://code.visualstudio.com/api/working-with-extensions/bundling-extension#using-esbuild)

Webpack is used both in the language server and the extension modules:

- https://github.com/wkillerud/some-sass/tree/main/packages/language-server
- https://github.com/wkillerud/some-sass/tree/main/vscode-extension

**Comment by tomasvn** [comment]
I had quite success with the speed of build, when I've set `cache` from `memory` to `filesystem`. Maybe you can take a look :)

https://webpack.js.org/configuration/cache/
