### ISSUE TITLE
Incorrect autocomplete when using a file that uses another file

### ISSUE THREAD

**Issue by dln-maurob** [wkillerud/some-sass#170]
- VS Code version: 1.87.1
- Extension version: 3.1.5
- Operating system: happens on both macOS and windows
- no other extensions enabled

Settings:
`"somesass.suggestFromUseOnly": true`

In the screenshot below it should suggest me `border.$color`, `border.$radius`, `border.$size`, ... Instead it suggests everything, including private variables, from the color file that is used by the border file.
<img width="1041" alt="Screenshot 2024-06-14 at 13 38 50" src="https://github.com/wkillerud/some-sass/assets/140403108/70750f40-6958-43a3-9d87-e968f6a567a8">

It works properly when importing a file that's not using anything else:
<img width="1041" alt="Screenshot 2024-06-14 at 13 40 19" src="https://github.com/wkillerud/some-sass/assets/140403108/1180c918-98da-43de-99e5-2710b9b43ff5">

**Comment by wkillerud** [comment]
Thanks for the bug report 🐛 Fix is out now in version 3.1.6.

**Comment by dln-maurob** [comment]
Thanks for the quick fix!
