### ISSUE TITLE
Autocomplete incorrectly suggests private SCSS variables

### ISSUE THREAD

**Issue by dln-maurob** [wkillerud/some-sass#172]
- VS Code version: 1.87.1
- Extension version: 3.1.6
- no other extensions enabled
- settings: `"somesass.suggestFromUseOnly": true`

When using a file that has private variables (prefixed with - or _), it will also suggests those. It only should suggest public variables however, as using private variables will cause compile errors. See [official docs](https://sass-lang.com/documentation/at-rules/use/#private-members) on private variables.

<img width="612" alt="Screenshot 2024-06-16 at 12 03 21" src="https://github.com/wkillerud/some-sass/assets/140403108/4e5a8d3b-2ac8-4494-a8b3-c73cb242a4ba">

**Comment by wkillerud** [comment]
Thanks for the heads-up. Didn't know that `-` were also considered private 😄

**Comment by wkillerud** [comment]
Fixed in 3.1.7
