### ISSUE TITLE
Autocomplete shows suggestions from all imported files

### ISSUE THREAD

**Issue by dln-maurob** [wkillerud/some-sass#173]
- VS Code version: 1.87.1
- Extension version: 3.1.6
- no other extensions enabled
- settings: `"somesass.suggestFromUseOnly": true`

When importing multiple files with `@use`, the suggestions are not limited to the one file you're trying to reference.
In the screenshot below, when typing `font.` I would expect to only see suggestions from the `_font.scss` file. Instead, it's also showing suggestions from the `_border.scss` file

<img width="1172" alt="Screenshot 2024-06-16 at 12 11 30" src="https://github.com/wkillerud/some-sass/assets/140403108/a7d93e42-a962-4bb4-b0bb-d82a5c9c680e">

**Comment by wkillerud** [comment]
Right, another regression that slipped by, thanks for the heads-up 🙌

**Comment by wkillerud** [comment]
Fixed in 3.1.7
