### ISSUE TITLE
Add support for code completion after `@debug` and `@error`

### ISSUE THREAD

**Issue by wkillerud** [wkillerud/some-sass#186]
From  #184

> I saw that typing on a line with `@debug` or `@error` would not show autocomplete suggestions

```scss
@use './test' as test;

$message: test. // it will show both suggestions here

@debug test. // it won't show anything here
@error test. // it won't show anything here
```

It's likely the `do-complete` feature gets confused by the at-rule statements. See if the [completion context](https://github.com/wkillerud/some-sass/blob/4095f8f2bffe1bcd17b0dc12a67ac0f2c238dd82/packages/language-services/src/features/do-complete.ts#L83) can be extended to support code completions in these two scenarios (`@debug` and `@error`).

**Comment by MenSeb** [comment]
Thank you for opening this issue.

Just in case I'll add that the at-rule `@warn` is also a problem.

Another case I found was:

```scss
@use './test' as test;

$test: "#{test.}"; // it won't show the autocomplete here after the dot

.#{test.} {} // it won't show the autocomplete here after the dot
```

```jsonc
// settings.json
{
    "somesass.suggestFunctionsInStringContextAfterSymbols": " (+-*%{"
}
```

I have a question regarding the option `suggestFunctionsInStringContextAfterSymbols` which I may not be using correctly. I tried the option by adding `{` to the default symbols without success. What I was looking for is to trigger the auctocomplete inside a string when using an expression like `#{...}`.

Please let me know if I'm doing something wrong and/or if you would like me to open another issue about this.

**Comment by wkillerud** [comment]
Sounds like a related issue, so we can track it here 👍 There's [some handling of string interpolation here](https://github.com/wkillerud/some-sass/blob/e28fa0379f985d911a66f7c33eda8cc34fdbf702/packages/language-services/src/features/do-complete.ts#L407), but I guess there are some cases where it doesn't work correctly.

**Comment by wkillerud** [comment]
Thanks for testing and reporting so thoroughly 🙌 

```scss
$test: "#{test.}";
```

For this case it seems like VS Code is not asking for code suggestions when I type inside the quotes, even after [this change](https://github.com/wkillerud/some-sass/pull/189/files#diff-9964dfb3f9ef4bd0fb20472c2c01bd23b05ce926070500b5aad207b930a8aeddR274), which I believe should make it so VS Code asks for completion items again.

A workaround is to manually ask for suggestions. [By default it should be Ctrl + Space](https://code.visualstudio.com/docs/editor/intellisense#_intellisense-features).

Another option is to skip the quotes. `$test: #{test.}` gives suggestions as expected in my testing.

**Comment by wkillerud** [comment]
Apart from what I [mention above](https://github.com/wkillerud/some-sass/issues/186#issuecomment-2256681536), the bugs describe in this issue should be fixed in [3.1.11](https://github.com/wkillerud/some-sass/releases/tag/some-sass%403.1.11).

**Comment by wkillerud** [comment]
About `suggestFunctionsInStringContextAfterSymbols`, it's a legacy from [scss-intellisense](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss) that covers some niche use cases. It's only purpose is to set [this flag here](https://github.com/wkillerud/some-sass/blob/14525ab1666f49b89725c06414cfb7c4e974f43d/packages/language-services/src/features/do-complete.ts#L472) in [these specific situations](https://github.com/wkillerud/some-sass/blob/14525ab1666f49b89725c06414cfb7c4e974f43d/packages/language-services/src/features/do-complete.ts#L461).

In your case inside the quotes you end up [here](https://github.com/wkillerud/some-sass/blob/14525ab1666f49b89725c06414cfb7c4e974f43d/packages/language-services/src/features/do-complete.ts#L476), and `isInterpolation` is `true`. You do get suggestions if you ask for them manually, so the problem is that VS Code doesn't ask for them for some reason.

**Comment by MenSeb** [comment]
Perfect, thanks for all the information!

I will update the extension, do more testing and get back to you in the new issue if needed.
