### ISSUE TITLE
Wrong setting in vscode-extension readme

### ISSUE THREAD

**Issue by MenSeb** [wkillerud/some-sass#187]
In the readme file from `vscode-extension` folder:

```jsonc
// Recommended if you don't rely on @import
	"somesass.suggestOnlyFromUse": true,
```

When it should be:

```jsonc
// Recommended if you don't rely on @import
	"somesass.suggestFromUseOnly": true,
```

I have a branch ready with the fix.

I looked at the contributing docs but I'm not sure about how you want me to push the branch.

**Comment by wkillerud** [comment]
Ah, you're right.

> I'm not sure about how you want me to push the branch.

A pull request to the `main` branch would be great. If you've worked with [conventional commits](https://github.com/wkillerud/some-sass/blob/main/CONTRIBUTING.md#conventional-commits) before, this would be a `docs: ` commit. If not, don't worry about it – I can sort out the commit name when I merge 😃
