### ISSUE TITLE
[Bug] Follow link doesn't work in VS code

### ISSUE THREAD

**Issue by tomasvn** [wkillerud/some-sass#206]
- **Operating system:** Windows 11
- **VS Code version:** `1.92.2`
- **Extension version:** `3.6.2`

Cannot add minimal repo, as it is a private repo.

Once disabled the extension, it works again.

With enabled extension
![Untitled](https://github.com/user-attachments/assets/fa1680c4-90f1-4c9c-93eb-e60b5733372b)

With disabled extension
![Untitled-1](https://github.com/user-attachments/assets/fd494b60-bcce-4874-88c5-418ec43708b4)

**Comment by tomasvn** [comment]
There must be some recent changes, as It used to work

**Comment by wkillerud** [comment]
Seems like a regression in 3.6.2. You can roll back to 3.6.1 via the Extensions menu in the mean time.

![](https://github.com/user-attachments/assets/9cf6dd97-2dae-4064-abe6-c8fbf8105f3a)

**Comment by wkillerud** [comment]
I'm pushing out a release that reverts 3.6.2 since this bug broke a lot of things. The server seems to be stuck in a loop.

**Comment by wkillerud** [comment]
3.6.3 seems to fix it, thanks for letting me know 👍
