### ISSUE TITLE
bug/feat: suggestions shown for SASS built-in modules global aliases

### ISSUE THREAD

**Issue by MenSeb** [wkillerud/some-sass#208]
- VS Code version: 1.92.2
- Extension version: 3.6.3
- Operating system: Windows

Reproducible Case:

https://github.com/MenSeb/some-sass-bug/tree/main/src/some-sass-suggestions

Steps to Reproduce:

```scss
// index.scss

@use '../modules' as *;

// This works correctly and is shown in suggestions
@debug color-blue(#fff);
@debug string-unique-id();

// Typing "co" will trigger the color-* prefixed suggestions.
// The "comparable" global function of the "sass:math" package is also shown.
@debug comparable($number1: 1, $number2: 2);
```

The built-in SASS modules global aliases are shown in suggestions even if the package itself was not called with `@use`.

From https://sass-lang.com/documentation/modules/

_Before the Sass module system was introduced, all Sass functions were globally available at all times. Many functions still have global aliases (these are listed in their documentation). The Sass team discourages their use and will eventually deprecate them, but for now they remain available for compatibility with older Sass versions and with LibSass (which doesn’t support the module system yet)._

I don't think this is a bug, but there could be a "nice to have" feature to prevent this.

Maybe as an option similar to `suggestFromUseOnly`, with something like `hideGlobalAliases` or `showGlobalAliases`, depending on whether the default behavior would be to hide or show them.

**Comment by wkillerud** [comment]
Sounds like this could follow the `suggestFromUseOnly`. Thanks for reporting 🙌

**Comment by wkillerud** [comment]
This one'll be a bit tricky as well. The built-in language server for CSS/SCSS/Less in VS Code also provides those suggestions, so even if we add this they won't go away completely in Code. Still worth doing on our part though, for sure 👍

**Comment by MenSeb** [comment]
> This one'll be a bit tricky as well. The built-in language server for CSS/SCSS/Less in VS Code also provides those suggestions, so even if we add this they won't go away completely in Code. Still worth doing on our part though, for sure 👍

I understand and confirm, it still shows when I disable the extension.

Is this why, when the extension is active, it displays duplicates in suggestions?

<img width="249" alt="image" src="https://github.com/user-attachments/assets/7a453e7f-740e-4c14-aeec-859940f0c11a">

We can see `abs` and `append` duplicated. I think I saw something about this in the documentation but I am not sure.

**Comment by wkillerud** [comment]
> Is this why, when the extension is active, it displays duplicates in suggestions?

Yes, though those duplicates could probably be removed somehow from Some Sass. Adding a note in my TODOs 👍
