### ISSUE TITLE
Highlighting errors when using version 3.7.0 with vue-official

### ISSUE THREAD

**Issue by Hazi7** [wkillerud/some-sass#223]
### In which editor is this a problem?

Visual Studio Code

### Describe the bug

This phenomenon occurs when I enable some sass, and disappears when I disable it.
<img width="466" alt="image" src="https://github.com/user-attachments/assets/8c359e06-2c4b-4962-8f92-cbac11ff0ffb">

### What's the expected result?

fixed highlighting error with vue-official

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wkillerud** [comment]
Thanks, fixed in 3.7.1
