### ISSUE TITLE
Tab completion merges namespace definition in Vue SFC style blocks inside Sublime Text

### ISSUE THREAD

**Issue by niksy** [wkillerud/some-sass#230]
### In which editor is this a problem?

Sublime Text

### Describe the bug

Following https://github.com/wkillerud/some-sass/issues/226, there is another similar issue if you’re using Sass language server for Vue SFC style blocks.

Namespace definition gets merged to autocompleted field instead of leaving dot.

[Language server](https://github.com/niksy/LSP-sass) `selector` needs to be set to `source.scss | text.html.vue` so language server gets applied to Vue SFC.

Take a look at the video:

https://github.com/user-attachments/assets/330626c8-147d-4ca6-b17c-c6d88d879182

### What's the expected result?

Dot separating namespace definition is left behind instead of being removed after completion.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wkillerud** [comment]
Hmm, that's unfortunate. In VSCode I had to work around Vue and friends to avoid duplicating the `.`. 

https://github.com/wkillerud/some-sass/blob/22a1e91ecaf4016b2db7a29c4f2be8edac5e946c/packages/language-services/src/features/do-complete.ts#L1176-L1179

I'll look into it, we'll probably need yet another setting 😅

**Comment by wkillerud** [comment]
Version [1.8.1](https://github.com/wkillerud/some-sass/releases/tag/some-sass-language-server%401.8.1) fixes this problem. It also makes the `somesass.completion.afterModule` and `somesass.completion.beforeVariable` settings obsolete (the internals of the code suggestions have been reworked so they're no longer needed).

**Comment by niksy** [comment]
Yup, this is it, thanks!
