### ISSUE TITLE
Colour Decorators is duplicated when defining the values

### ISSUE THREAD

**Issue by yCodeTech** [wkillerud/some-sass#233]
### In which editor is this a problem?

Visual Studio Code

### Describe the bug

The colour decorators are duplicated when defining colour values to variables but are not duplicated when using the colour variables.

I have rolled back a couple of versions and found that it functions correctly in v3.6.4; all version afterwards the decorators are shown twice. Please refer to the screenshot below for the bug in action in the latest version (v3.9.0).

![image](https://github.com/user-attachments/assets/01742b35-e7c7-4bb1-b1db-22be696e6833)

### What's the expected result?

The colour decorator is shown only once.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by niksy** [comment]
Same issue in Sublime Text.

**Comment by wkillerud** [comment]
Strange, this is what I'm seeing in VS Code (left) and Sublime Text (right) with the current release (3.9.0 of the extension, 1.8.0 of the language server).

![screenshot showing both editors with no duplicate color decorators](https://github.com/user-attachments/assets/328ae00b-1649-477a-8a1b-3a250cf458e9)

Does the same happen if you turn off other extensions? And can you share your settings if you use anything other than the defaults?

**Comment by niksy** [comment]
This happens in Sublime Text if you have CSS and Sass language server active for the current context.

I’ve [added information about this and how to bypass it in LSP-sass](https://github.com/niksy/LSP-sass#duplicate-link-and-color-definitions-when-using-css-language-server), but this works best with workspaces, but conflicts with situations where you could have CSS and Sass files in project and then you wouldn’t have color information.

Disabling `colorProvider` for Sass language server removes color hints for Sass variables so this can’t be focused only on Sass language server context, it must be applied to CSS language server to work properly.

One possibility is if Sass language server could fully extend CSS language server so you get all completions and property types and then CSS language server could be disabled for Sass files. I don’t know if that’s possible or is that something that conflicts with how VS Code implementation works.

**Comment by wkillerud** [comment]
I see, thanks for elaborating @niksy – that makes sense. I'll try to reproduce again in Sublime (and double check my own settings in Code – maybe I turned off something of the built-in stuff 😅).

> One possibility is if Sass language server could fully extend CSS language server so you get all completions and property types and then CSS language server could be disabled for Sass files. I don’t know if that’s possible or is that something that conflicts with how VS Code implementation works.

This has been on my "maybe some day" list for a while, to make this language server "fully operational" if you will 😄 Especially now, since we have all those features for the Indented syntax. The code is there, it's "just" a matter of turning it on for SCSS and CSS as well.

It is possible for a user to turn off the built-in CSS features in Code. Another option is to have settings for features that conflict with the VS Code CSS language server, and have them default off only for the VS Code extension/language client.

**Comment by yCodeTech** [comment]
In VS Code, the built-in CSS Language Features that also provides colour/color picker for the colour values. Disabling this built-in extension removes the 2nd colour picker, but also removes other css related intellisense, so this isn't feasible.

I can see there is a setting within Some Sass "Suggest All from Open Document" to enable it's code suggestions from this extension. Disabling this also removes the 2nd colour picker, but considering I don't know what other suggestions/intellisense I'm disabling for SCSS with Some Sass, then this also isn't feasible. (Plus I don't have any duplicate suggestions that I can see, so there is no other reason to disable this.)

>  Another option is to have settings for features that conflict with the VS Code CSS language server, and have them default off only for the VS Code extension/language client.

I think this would be the best way to go. So a completely separate setting to disable the duplicated colour picker would be perfect, and ensures all other extension suggestions are enabled.

**Comment by wkillerud** [comment]
I shipped a quick fix for VS Code and opened #236 for the longer-term improvements we discussed 👍
