### ISSUE TITLE
Let `some-sass-language-server` handle all features for CSS and SCSS

### ISSUE THREAD

**Issue by wkillerud** [wkillerud/some-sass#236]
The "contract" for `some-sass-language-server` right now is that it should behave well (ish) with `vscode-css-language-server` running and providing features for SCSS in the same editor (basically mirror what happens in VS Code out of the box). Unfortunately that's not always the case (#233), and in a way it makes it more complicated to configure editors that don't ship with `vscode-css-language-server` built in.

We want to change the language server so it handles all features for CSS, SCSS and Sass indented by default (provided the editor is configured to run `some-sass-language-server` for them). This is considered a breaking change, meaning a new semver major version.

Editors that don't ship with `vscode-css-language-server` will have an easier time configuring SCSS, Sass indented, and the option of using this server also for CSS.

For editors that _do_ ship with `vscode-css-language-server` turned on by default for SCSS (VS Code, VSCodium, perhaps others):

- the out-of-the-box experience should be similar to the current behavior (features handled by `vscode-css-language-server` should be turned off in `some-sass` by default).
- the user should be able to turn off `vscode-css-language-server` and configure `some-sass` to handle everything.

**Comment by wkillerud** [comment]
Since this will be a breaking change I want to take some time to consider other breaking changes, like how the settings are named and organized, and perhaps drop the `development` export from the published module.

**Comment by niksy** [comment]
Just wanted to thank you for this, it seems like standalone Sass server now works even better since it can handle all CSS and Sass related tasks!
