### ISSUE TITLE
Color references not always working in Sublime Text

### ISSUE THREAD

**Issue by niksy** [wkillerud/some-sass#252]
### In which editor is this a problem?

Sublime Text

### Describe the bug

When using only Sass LSP this is what code looks like:

![Screenshot 2024-10-05 at 12 03 35](https://github.com/user-attachments/assets/1e1785af-ac53-4fca-b9e0-3e3a20e2dc66)

Compare it with when CSS LSP is also used for that same code:

![Screenshot 2024-10-05 at 12 02 33](https://github.com/user-attachments/assets/09687248-ed2c-41f8-8c1b-009dd9cc6cfe)

Notice how `$hello` variable gets it’s value recognized as color.

I tried setting enabling `somesass.css.colors.enabled` but it doesn’t do anything.

### What's the expected result?

Colors are always recognized inside code.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wkillerud** [comment]
Hi @niksy

I installed the latest LSP-sass and noticed the default setting [`somesass.scss.colors.includeFromCurrentDocument`](https://github.com/niksy/LSP-sass/blob/a9b1d2d0ae39e2b333b11f5544f082ed4d1f616d/LSP-sass.sublime-settings#L14) is set to `false`. The setting name is a bit imprecise, looking at it now. If you set it to `true` it will turn on color decorators for SCSS variable declarations and CSS colors in the open SCSS document.

This is with the setting set to `true`.

![a variable declaration with a red color decorator next to it](https://github.com/user-attachments/assets/7bf9acff-a0c0-4a97-81a3-ffcd7de6d6c1)

**Comment by niksy** [comment]
Yes, I’ve been using defaults from https://wkillerud.github.io/some-sass/user-guide/settings.html where that value is mentioned as false by default. Is this not true? Should this be updated?

Where can we find full default values list? Is it this file: https://github.com/wkillerud/some-sass/blob/main/packages/language-services/src/configuration.ts

**Comment by wkillerud** [comment]
> Yes, I’ve been using defaults from https://wkillerud.github.io/some-sass/user-guide/settings.html where that value is mentioned as false by default. Is this not true? Should this be updated?

It's correct for the Visual Studio Code extension, which has different defaults from the language server itself. You highlight a good point though. Correct documentation of settings default values is missing for language server users.

> Where can we find full default values list? Is it this file: https://github.com/wkillerud/some-sass/blob/main/packages/language-services/src/configuration.ts

Yes, those are the default settings used by the language server.

**Comment by niksy** [comment]
Okay, this is it. Now I need to figure out how to disable Volar color implementation and leave only Some Sass active.

![Screenshot 2024-10-07 at 20 06 24](https://github.com/user-attachments/assets/88b8b913-70b0-4265-b300-86e6c3d35b34)

**Comment by niksy** [comment]
Okay, closing this since this is now fixed, Volar related issue is a different beast :)

**Comment by niksy** [comment]
Seems like it can be Sublime LSP issue: https://github.com/sublimelsp/LSP/issues/2534
