### ISSUE TITLE
custom at-rules show warnings

### ISSUE THREAD

**Issue by remchoi** [wkillerud/some-sass#275]
### In which editor is this a problem?

Visual Studio Code

### Describe the bug

I defined a custom `@at-rule` within `.vscode/css-data.json`
```json
{
    "version": 1.1,
    "atDirectives": [
        {
            "name": "@define-props",
            "description": "Framework based props"
        }
    ]
}
``` 
also added reference to vs code settings
```json
"somesass.css.customData": [
   "./.vscode/css-data.json"
],
"css.customData": [
   "./.vscode/css-data.json"
]
```
despite this I still got a warning when using this rule
<img width="734" alt="Screenshot 2024-12-07 at 15 46 38" src="https://github.com/user-attachments/assets/a97fb393-6d50-4683-b915-804a6812595e">

Note that default vscode annotation ("Framework based props") is displayed correctly.

### What's the expected result?

No warnings for custom at-rules

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wkillerud** [comment]
Thank you for the bug report. This has been fixed in [version 4.1.1](https://github.com/wkillerud/some-sass/releases/tag/some-sass%404.1.1).
