### ISSUE TITLE
Cannot disable warnings about unknown at rules

### ISSUE THREAD

**Issue by archasek** [wkillerud/some-sass#276]
### In which editor is this a problem?

Visual Studio Code

### Describe the bug

I have in .vscode/settings.json
`"somesass.scss.diagnostics.lint.unknownAtRules": "ignore"`

no matter if I use that setting or not I still see the warning:
![{C4622B72-DDD0-432F-B6F9-F49536827A0F}](https://github.com/user-attachments/assets/acb8df88-ec27-45bb-a244-c212018d7669)

in extension ui settings there's:
![{FC7E647A-CC8F-43B6-B9AF-C57DB505C0EE}](https://github.com/user-attachments/assets/17d18f7c-d915-4e7e-bc97-e4cc83dae087)
(doesn't work even if I set it here to ignore as well)

### What's the expected result?

no warnings ;)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wkillerud** [comment]
Thank you for the bug report. This has been fixed in [version 4.1.1](https://github.com/wkillerud/some-sass/releases/tag/some-sass%404.1.1).

**Comment by archasek** [comment]
Thank you legend

**Comment by PixsaOJ** [comment]
How can i do this for neovim lsp options?
